# Site setings
name: 'Aryn Alexandra'
description: 'nelson/writer'
# Sidebar about text
site_description: 'nelson/writer'
logo:
favicon: 'assets/images/favicon.ico'
baseurl:
production_url: https://aryn.ca
disqus:
mailchimp_url:
# Add your GA Tracking Id
ga_analytics:

# Contact form setings
email: hey@aryn.ca
contact_page_description:
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter:
facebook:
github:
codepen:
dribbble:
medium:
instagram: 'https://www.instagram.com/arynalexa'
pinterest:
linkedin:

# Navigation
navigation:
  - text: About
    url: /about
  - text: Style Guide
    url: /style-guide
  - text: Contact
    url: /contact

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 6
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "gallery"
    values:
      layout: "gallery"
